ignore:
    - "hwlocality-sys/build.rs"

codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        threshold: 0.2
    patch:
      default:
        threshold: 0.5
